AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ACME Package Registry - Trustworthy Model Registry API

Globals:
  Function:
    Timeout: 300
    MemorySize: 2048
    Runtime: python3.13  # Change to match your Python version
    Environment:
      Variables:
        GIT_LFS_SKIP_SMUDGE: "1"
        HF_HUB_DISABLE_PROGRESS_BARS: "1"
        MIN_NET_SCORE: "0.5"
        # Configure HuggingFace to use Lambda's writable /tmp directory
        HF_HOME: "/tmp/huggingface"
        HUGGINGFACE_HUB_CACHE: "/tmp/huggingface/hub"
        TRANSFORMERS_CACHE: "/tmp/huggingface/transformers"
        # Add your HuggingFace token here or set via parameter
        # HF_TOKEN: !Ref HuggingFaceToken

Parameters:
  HuggingFaceToken:
    Type: String
    Description: HuggingFace API token for accessing models
    NoEcho: true
    Default: ""

Resources:
  # S3 Bucket for artifact storage
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "acme-registry-artifacts-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

  # S3 Bucket for static website hosting
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "acme-registry-frontend-${AWS::AccountId}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: true
        IgnorePublicAcls: false
        RestrictPublicBuckets: true

  # Bucket policy for public read access to website
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${WebsiteBucket.Arn}/*'

  # Lambda Function for POST /artifact/{artifact_type}
  CreateArtifactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handlers.create_artifact.handler
      Description: Register a new artifact (model/dataset/code)
      FunctionName: acme-registry-create-artifact
      Environment:
        Variables:
          HF_TOKEN: !Ref HuggingFaceToken
          ARTIFACTS_BUCKET: !Ref ArtifactsBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref ArtifactsBucket

  # Lambda Function for GET /artifact/model/{id}/rate
  RateArtifactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handlers.rate_artifact.handler
      Description: Get ratings for a model artifact
      FunctionName: acme-registry-rate-artifact
      Environment:
        Variables:
          HF_TOKEN: !Ref HuggingFaceToken
          ARTIFACTS_BUCKET: !Ref ArtifactsBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ArtifactsBucket

  # Lambda Function for GET /health
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handlers.health_check.handler
      Description: Health check endpoint
      FunctionName: acme-registry-health-check
      Timeout: 10
      MemorySize: 128

  # Lambda Function for GET /artifact/byName/{name}
  GetArtifactByNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handlers.get_artifact_by_name.handler
      Description: Get artifacts by name
      FunctionName: acme-registry-get-artifact-by-name
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          ARTIFACTS_BUCKET: !Ref ArtifactsBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ArtifactsBucket

  # Lambda Function for POST /artifacts
  ListArtifactsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handlers.list_artifacts.handler
      Description: List artifacts with pagination and filtering
      FunctionName: acme-registry-list-artifacts
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          ARTIFACTS_BUCKET: !Ref ArtifactsBucket
          ARTIFACTS_PAGE_SIZE: "50"
          ARTIFACTS_MAX_RESULTS: "250"
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ArtifactsBucket

  # Lambda Function for DELETE /reset
  ResetRegistryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handlers.reset_registry.handler
      Description: Reset registry by deleting all artifacts
      FunctionName: acme-registry-reset
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          ARTIFACTS_BUCKET: !Ref ArtifactsBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ArtifactsBucket

Outputs:
  CreateArtifactFunctionArn:
    Description: "Create Artifact Lambda Function ARN"
    Value: !GetAtt CreateArtifactFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CreateArtifactFunctionArn"

  CreateArtifactFunctionName:
    Description: "Create Artifact Lambda Function Name"
    Value: !Ref CreateArtifactFunction

  RateArtifactFunctionArn:
    Description: "Rate Artifact Lambda Function ARN"
    Value: !GetAtt RateArtifactFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RateArtifactFunctionArn"

  RateArtifactFunctionName:
    Description: "Rate Artifact Lambda Function Name"
    Value: !Ref RateArtifactFunction

  HealthCheckFunctionArn:
    Description: "Health Check Lambda Function ARN"
    Value: !GetAtt HealthCheckFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-HealthCheckFunctionArn"

  HealthCheckFunctionName:
    Description: "Health Check Lambda Function Name"
    Value: !Ref HealthCheckFunction

  GetArtifactByNameFunctionArn:
    Description: "Get Artifact By Name Lambda Function ARN"
    Value: !GetAtt GetArtifactByNameFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-GetArtifactByNameFunctionArn"

  GetArtifactByNameFunctionName:
    Description: "Get Artifact By Name Lambda Function Name"
    Value: !Ref GetArtifactByNameFunction

  ArtifactsBucketName:
    Description: "S3 Bucket for artifact storage"
    Value: !Ref ArtifactsBucket

  ListArtifactsFunctionArn:
    Description: "List Artifacts Lambda Function ARN"
    Value: !GetAtt ListArtifactsFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ListArtifactsFunctionArn"

  ListArtifactsFunctionName:
    Description: "List Artifacts Lambda Function Name"
    Value: !Ref ListArtifactsFunction

  ResetRegistryFunctionArn:
    Description: "Reset Registry Lambda Function ARN"
    Value: !GetAtt ResetRegistryFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ResetRegistryFunctionArn"

  ResetRegistryFunctionName:
    Description: "Reset Registry Lambda Function Name"
    Value: !Ref ResetRegistryFunction

  WebsiteBucketName:
    Description: "S3 Bucket for static website"
    Value: !Ref WebsiteBucket

  WebsiteUrl:
    Description: "Static website URL for front-end"
    Value: !GetAtt WebsiteBucket.WebsiteURL
