AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ACME Package Registry - Trustworthy Model Registry API

Globals:
  Function:
    Timeout: 300
    MemorySize: 2048
    Runtime: python3.13  # Change to match your Python version
    Environment:
      Variables:
        GIT_LFS_SKIP_SMUDGE: "1"
        HF_HUB_DISABLE_PROGRESS_BARS: "1"
        MIN_NET_SCORE: "0.5"
        # Configure HuggingFace to use Lambda's writable /tmp directory
        HF_HOME: "/tmp/huggingface"
        HUGGINGFACE_HUB_CACHE: "/tmp/huggingface/hub"
        TRANSFORMERS_CACHE: "/tmp/huggingface/transformers"
        # Add your HuggingFace token here or set via parameter
        # HF_TOKEN: !Ref HuggingFaceToken

Parameters:
  HuggingFaceToken:
    Type: String
    Description: HuggingFace API token for accessing models
    NoEcho: true
    Default: ""

Resources:
  # Lambda Function for POST /artifact/{artifact_type}
  CreateArtifactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handlers.create_artifact
      Description: Register a new artifact (model/dataset/code)
      FunctionName: acme-registry-create-artifact
      Environment:
        Variables:
          HF_TOKEN: !Ref HuggingFaceToken

  # Lambda Function for GET /artifact/model/{id}/rate
  RateArtifactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handlers.rate_artifact
      Description: Get ratings for a model artifact
      FunctionName: acme-registry-rate-artifact
      Environment:
        Variables:
          HF_TOKEN: !Ref HuggingFaceToken

  # Lambda Function for GET /health
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handlers.health_check
      Description: Health check endpoint
      FunctionName: acme-registry-health-check
      Timeout: 10
      MemorySize: 128

Outputs:
  CreateArtifactFunctionArn:
    Description: "Create Artifact Lambda Function ARN"
    Value: !GetAtt CreateArtifactFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CreateArtifactFunctionArn"

  CreateArtifactFunctionName:
    Description: "Create Artifact Lambda Function Name"
    Value: !Ref CreateArtifactFunction

  RateArtifactFunctionArn:
    Description: "Rate Artifact Lambda Function ARN"
    Value: !GetAtt RateArtifactFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RateArtifactFunctionArn"

  RateArtifactFunctionName:
    Description: "Rate Artifact Lambda Function Name"
    Value: !Ref RateArtifactFunction

  HealthCheckFunctionArn:
    Description: "Health Check Lambda Function ARN"
    Value: !GetAtt HealthCheckFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-HealthCheckFunctionArn"

  HealthCheckFunctionName:
    Description: "Health Check Lambda Function Name"
    Value: !Ref HealthCheckFunction
